// Group A of the #124 case table (docs/maintainers/case-tables/124-friction-sweep.md),
// implemented by #380: what differed from expectation stops being a sentence
// buried in report prose and becomes `payload.friction`, a list of sentences
// on the report event itself.
//
// Each test below is one cell, named by its number. Cells A1–A6 are capture,
// A7–A10 are the four surfaces a report is read from, A11–A12 are the gates
// and the store that predates the flag, and A13 is the gap the design chose to
// leave open rather than close with a second required flag.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { demoWorkspace, machine, must, mustPerson, selfIn, workIdIn } from "./harness.mjs";

const box = machine();
const { ws, demo } = await demoWorkspace(box);
const log = join(ws, ".superself", "projects", "demo", "log.jsonl");

let seq = 0;

async function freshUnit()
{
    seq += 1;
    return workIdIn((await mustPerson(box, demo, ["work", "add", `outcome ${seq}`])).out);
}

function reportsOf(id)
{
    return readFileSync(log, "utf8")
        .split("\n")
        .filter((line) => line.trim() !== "")
        .map((line) => JSON.parse(line))
        .filter((event) => event.type === "report.added" && event.refs.work === id);
}

function onlyReportOf(id)
{
    const found = reportsOf(id);
    assert.equal(found.length, 1, `expected one report on ${id}, got ${found.length}`);
    return found[0];
}

test("A1: a report with no --friction records exactly as it always did", async () =>
{
    const id = await freshUnit();
    assert.equal((await selfIn(box, demo, ["report", id, "the suite went green"])).code, 0);
    const payload = onlyReportOf(id).payload;
    assert.equal(payload.text, "the suite went green");
    assert.ok(!("friction" in payload), `an absent flag still wrote a key: ${JSON.stringify(payload)}`);
});

test("A2: one --friction lands as a one-element array", async () =>
{
    const id = await freshUnit();
    const said = "the root suite took 25 minutes, not the 12 CONTRIBUTING states";
    assert.equal((await selfIn(box, demo, ["report", id, "phase one done", "--friction", said])).code, 0);
    assert.deepEqual(onlyReportOf(id).payload.friction, [said]);
});

test("A3: two --friction keep their order", async () =>
{
    const id = await freshUnit();
    const result = await selfIn(box, demo, ["report", id, "phase two done",
        "--friction", "the fixture had to be regenerated by hand",
        "--friction", "the brief re-instructed a discipline already written down"]);
    assert.equal(result.code, 0, result.out);
    assert.deepEqual(onlyReportOf(id).payload.friction, [
        "the fixture had to be regenerated by hand",
        "the brief re-instructed a discipline already written down"
    ]);
});

test("A4: an empty --friction is refused, and the refusal says what to write", async () =>
{
    const id = await freshUnit();
    const result = await selfIn(box, demo, ["report", id, "phase three done", "--friction", ""]);
    assert.equal(result.code, 1, result.out);
    assert.match(result.out, /--friction takes one sentence saying what differed from expectation/);
    assert.match(result.out, /or leave the flag off/);
    assert.equal(reportsOf(id).length, 0, "a refused report still wrote an event");
});

test("A5: a whitespace-only --friction is refused the same way", async () =>
{
    const id = await freshUnit();
    const result = await selfIn(box, demo, ["report", id, "phase four done", "--friction", "   "]);
    assert.equal(result.code, 1, result.out);
    assert.match(result.out, /--friction takes one sentence saying what differed from expectation/);
    assert.equal(reportsOf(id).length, 0, "a refused report still wrote an event");
});

// The exclusion the design writes belongs to the sweep, not to capture: "as
// expected" is a real answer to the question, and refusing it here would make
// the honest report the one the CLI rejects.
test("A6: 예상대로 records like any other sentence", async () =>
{
    const id = await freshUnit();
    assert.equal((await selfIn(box, demo, ["report", id, "phase five done", "--friction", "예상대로"])).code, 0);
    assert.deepEqual(onlyReportOf(id).payload.friction, ["예상대로"]);
});

// A7, A10 and A9 share one unit, because the three surfaces answer for the
// same recorded report and building three would prove less, not more.
const READ_UNIT = { id: null, said: "the golden fixture needed regenerating, which the plan had not budgeted" };

test("A7: work show carries the friction line", async () =>
{
    READ_UNIT.id = await freshUnit();
    await must(box, demo, ["report", READ_UNIT.id, "the read surfaces answer", "--friction", READ_UNIT.said]);
    const out = (await must(box, demo, ["work", "show", READ_UNIT.id])).out;
    assert.ok(out.includes(`friction: ${READ_UNIT.said}`), `work show lost the friction line:\n${out}`);
});

test("A8: the handoff packet carries the friction", async () =>
{
    const out = (await must(box, demo, ["handoff", READ_UNIT.id])).out;
    assert.ok(out.includes(`friction: ${READ_UNIT.said}`), `the handoff packet lost the friction:\n${out}`);
});

test("A9: self log prints the report as one line carrying its friction", async () =>
{
    const out = (await must(box, demo, ["log", "-n", "40"])).out;
    const line = out.split("\n").find((row) => row.includes("report.added") && row.includes("the read surfaces answer"));
    assert.ok(line !== undefined, `no report line for ${READ_UNIT.id} in:\n${out}`);
    assert.ok(!line.trimStart().startsWith("{"), `the log printed raw JSON: ${line}`);
    assert.ok(line.includes(`(friction: ${READ_UNIT.said})`), `the log line lost the friction: ${line}`);
});

test("A10: the canonical work page carries the friction line", () =>
{
    const page = readFileSync(join(ws, ".superself", "projects", "demo", "work", `${READ_UNIT.id}.md`), "utf8");
    assert.ok(page.includes(`- friction: ${READ_UNIT.said}`), `work/<id>.md lost the friction line:\n${page}`);
});

// The gate that already guards every recorded string guards this one too, so
// #380 adds no check of its own. What is asserted here is that the flag is
// inside the gate's reach and that the refusal names where the path was — the
// writer's only way to know which of several strings to rewrite.
test("A11: a home absolute path in a friction sentence is refused by the existing gate", async () =>
{
    const id = await freshUnit();
    const result = await selfIn(box, demo, ["report", id, "phase six done",
        "--friction", `the failure was in ${box.env.HOME}/ws/demo/src/main.ts and nothing said so`]);
    assert.equal(result.code, 1, result.out);
    assert.match(result.out, /payload\.friction\[0\]/);
    assert.match(result.out, /absolute path under this machine's home directory/);
    assert.equal(reportsOf(id).length, 0, "a refused report still wrote an event");
});

// A store written before the flag existed: A1's report is exactly that shape,
// and a refold has to give it an empty list rather than an absent field a
// renderer would then have to guard.
test("A12: a report with no friction key folds to an empty list, with no error", async () =>
{
    const id = await freshUnit();
    await must(box, demo, ["report", id, "a report from before the flag"]);
    assert.equal((await must(box, demo, ["fold"])).code, 0);
    const page = readFileSync(join(ws, ".superself", "projects", "demo", "work", `${id}.md`), "utf8");
    assert.ok(page.includes("a report from before the flag"), page);
    assert.ok(!page.includes("friction:"), `a report with no friction rendered a friction line:\n${page}`);
    assert.ok(!(await must(box, demo, ["handoff", id])).out.includes("friction:"));
});

// The known gap, asserted so it stays known. `work done --report` writes a
// report.added of its own and takes no --friction; requiring friction would
// have made this path a bypass, so the design left it a gap the nudge counts
// instead of adding a second gate on the done path.
test("A13: work done --report records a report with no friction", async () =>
{
    const id = await freshUnit();
    await must(box, demo, ["work", "start", id]);
    await must(box, demo, ["work", "done", id, "--report", "the outcome verifiably holds"]);
    const payloads = reportsOf(id).map((event) => event.payload);
    assert.equal(payloads.length, 1);
    assert.equal(payloads[0].text, "the outcome verifiably holds");
    assert.ok(!("friction" in payloads[0]), `work done --report wrote a friction key: ${JSON.stringify(payloads[0])}`);
    assert.notEqual((await selfIn(box, demo, ["work", "done", id, "--report", "x", "--friction", "y"])).code, 0,
        "work done accepted --friction, which the design says it does not take");
});
