import { createHash } from "node:crypto";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { refreshBlocks } from "./connect.js";
import { buildModel, DecisionState, ProjectModel, WorkState } from "./model.js";
import { ensureDir, projectStateDir, resolveProjectPath } from "./paths.js";
import { writeViews } from "./view.js";

const GENERATED_NOTE = "<!-- generated by `self` — do not edit; state changes go through events -->";

export function foldProject(storeDir: string, slug: string): void
{
    const model = buildModel(storeDir, slug, new Date());
    const dir = ensureDir(projectStateDir(storeDir, slug));
    ensureDir(join(dir, "work"));
    const hashes = readHashes(dir);
    writeGenerated(dir, hashes, "state.md", renderState(model));
    for (const work of model.works)
    {
        const rel = join("work", `${work.id}.md`);
        if (work.status === "done")
        {
            rmSync(join(dir, rel), { force: true });
            delete hashes[rel];
        }
        else
        {
            writeGenerated(dir, hashes, rel, renderWork(work));
        }
    }
    writeFileSync(join(dir, ".hashes.json"), JSON.stringify(hashes, null, 2) + "\n");
    writeViews(storeDir, model);
    const projectDir = resolveProjectPath(storeDir, slug);
    if (projectDir !== null && existsSync(projectDir))
    {
        refreshBlocks(projectDir, model);
    }
}

function readHashes(dir: string): Record<string, string>
{
    const file = join(dir, ".hashes.json");
    return existsSync(file) ? JSON.parse(readFileSync(file, "utf8")) : {};
}

function writeGenerated(dir: string, hashes: Record<string, string>, rel: string, content: string): void
{
    const file = join(dir, rel);
    const recorded = hashes[rel];
    if (recorded !== undefined && existsSync(file) && sha(readFileSync(file, "utf8")) !== recorded)
    {
        console.error(`warning: ${rel} was edited by hand — overwriting; state changes must go through events`);
    }
    writeFileSync(file, content);
    hashes[rel] = sha(content);
}

function sha(content: string): string
{
    return createHash("sha256").update(content).digest("hex");
}

function renderState(model: ProjectModel): string
{
    const lines: string[] = [GENERATED_NOTE, "", `# ${model.slug}`, ""];
    if (model.description !== undefined)
    {
        lines.push(model.description, "");
    }
    lines.push("## Goal", "", model.goal ?? "_not set_", "");
    section(lines, "Decisions", decisionLines(model.decisions.filter((d) => d.status === "confirmed")));
    section(lines, "Proposed decisions", proposalLines(model.decisions));
    section(lines, "Conventions", model.conventions.map((c) => `- ${c.text} _(${c.id})_`));
    section(lines, "Work in progress", model.works.filter((w) => w.status === "active").map(workLine));
    section(lines, "Blocked", model.works.filter((w) => w.status === "blocked").map(blockedLine));
    section(lines, "Next", model.works.filter((w) => w.status === "next").map((w) => `- **${w.id}** ${w.outcome}`));
    section(lines, "Open questions", model.openQuestions.map((q) => `- ${q}`));
    section(lines, "Health", model.health.map((h) => `- ${h}`));
    return lines.join("\n").replace(/\n+$/, "\n");
}

function section(lines: string[], title: string, items: string[]): void
{
    if (items.length === 0)
    {
        return;
    }
    lines.push(`## ${title}`, "", ...items, "");
}

function decisionLines(decisions: DecisionState[]): string[]
{
    return decisions.map((decision) =>
    {
        const why = decision.why === undefined ? "" : ` — ${decision.why}`;
        return `- ${decision.text}${why} _(${day(decision.ts)}, ${decision.id})_`;
    });
}

function proposalLines(decisions: DecisionState[]): string[]
{
    return decisions
        .filter((decision) => decision.status === "proposed" && !decision.expired)
        .map((decision) => `- ${decision.text} _(proposed ${day(decision.ts)} — \`self decide confirm ${decision.id}\`)_`);
}

function workLine(work: WorkState): string
{
    const latest = work.reports[work.reports.length - 1];
    const report = latest === undefined ? "" : ` — ${latest.text}`;
    const next = work.next === undefined ? "" : ` (next: ${work.next})`;
    return `- **${work.id}** ${work.outcome}${report}${next}`;
}

function blockedLine(work: WorkState): string
{
    const why = work.blockedWhy === undefined ? "" : `: ${work.blockedWhy}`;
    return `- **${work.id}** ${work.outcome} — waiting on ${work.blockedOn}${why}`;
}

function renderWork(work: WorkState): string
{
    return GENERATED_NOTE + "\n\n" + renderWorkBody(work);
}

export function renderWorkBody(work: WorkState): string
{
    const lines: string[] = [`# ${work.id} — ${work.outcome}`, "", `- Status: ${work.status}`];
    if (work.status === "blocked")
    {
        lines.push(`- Blocked on: ${work.blockedOn}${work.blockedWhy === undefined ? "" : ` — ${work.blockedWhy}`}`);
    }
    if (work.next !== undefined)
    {
        lines.push(`- Next action: ${work.next}`);
    }
    if (work.evidence.length > 0)
    {
        lines.push(`- Evidence: ${work.evidence.join(", ")}`);
    }
    lines.push("");
    if (work.reports.length > 0)
    {
        lines.push("## Reports (latest first)", "");
        for (const report of [...work.reports].reverse())
        {
            const commits = report.commits.length > 0 ? ` [${report.commits.join(", ")}]` : "";
            if (report.text.includes("\n"))
            {
                lines.push(`### ${day(report.ts)}${commits}`, "", report.text, "");
            }
            else
            {
                lines.push(`- ${day(report.ts)} — ${report.text}${commits}`);
            }
        }
        lines.push("");
    }
    return lines.join("\n").replace(/\n+$/, "\n");
}

function day(ts: string): string
{
    return ts.slice(0, 10);
}
