import { createHash } from "node:crypto";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { refreshBlocks } from "./connect.js";
import { branchLabel, branchTotals, buildModel, currentConventions, DecisionState, foreignToward, liveGoals, ProjectModel, unshippedBranches, WorkState } from "./model.js";
import { contributionsOf, Coverage, MilestoneState, ObjectiveState, openObjectives, openProposals, Reached } from "./objectives.js";
import { notice } from "./output.js";
import { ensureDir, projectStateDir, PrunedLink, pruneDeadLinks, readRegistry, readStoreConfig, resolveProjectPath, resolveProjectPaths, Verdict } from "./paths.js";
import { artifactSignals, askedRepositories, evidenceOf, updateVerdicts, verdictSignals } from "./reachability.js";
import { errYellow } from "./style.js";
import { chromeStale, claimChrome, writeViews } from "./view.js";

const GENERATED_NOTE = "<!-- generated by `self` — do not edit; state changes go through events -->";

// What an event append derives, and what it deliberately leaves for a
// workspace sweep. Every event append runs this, so anything added here is
// paid for by `self work add` and by every other verb (#128).
//
// An append updates, for the one project the event belongs to: its canonical
// markdown, its evidence verdicts, its JSON summary and HTML pages, the
// workspace index page — which is rendered from the per-project summaries
// already on disk, so it is current for every project without folding any of
// them — and the managed agent block in the checkout the command ran from.
//
// An append does not touch any other project's pages, and does not prune dead
// links. Both belong to the workspace sweep below — `foldWorkspace` for
// `self fold`, `foldEveryProject` for `self sync`, `self clone` and a
// view-setting change. Nothing a person reads on a console goes stale for it:
// `self context`, `self status` and `self work` build their model from the log
// rather than from these files.
export function foldProject(storeDir: string, slug: string): void
{
    const model = buildModel(storeDir, slug, new Date());
    const projectDir = resolveProjectPath(storeDir, slug);
    const verdicts = judgeEvidence(storeDir, slug, model);
    const dir = ensureDir(projectStateDir(storeDir, slug));
    ensureDir(join(dir, "work"));
    const hashes = readHashes(dir);
    writeGenerated(dir, hashes, "state.md", renderState(model));
    for (const work of model.works)
    {
        const rel = join("work", `${work.id}.md`);
        if (work.status === "done" || work.status === "retired")
        {
            drop(dir, hashes, rel);
        }
        else
        {
            writeGenerated(dir, hashes, rel, renderWork(work, model, verdicts));
        }
    }
    foldObjectives(dir, hashes, model);
    writeFileSync(join(dir, ".hashes.json"), JSON.stringify(hashes, null, 2) + "\n");
    writeViews(storeDir, model, readStoreConfig(storeDir), verdicts);
    if (projectDir !== null && existsSync(projectDir))
    {
        refreshBlocks(projectDir, model);
    }
}

// Verdicts across every repository the project is linked to here (#331), and
// the health lines they raise, folded into the model the pages render from.
function judgeEvidence(storeDir: string, slug: string, model: ProjectModel): Record<string, Verdict>
{
    const verdicts = updateVerdicts(storeDir, slug, resolveProjectPaths(storeDir, slug), evidenceOf(model.works));
    model.health.push(...verdictSignals(model.works, verdicts, askedRepositories(storeDir, slug)),
        ...artifactSignals(storeDir, model.works));
    return verdicts;
}

// The workspace sweep. It owns the two jobs an append must not carry: bringing
// every other project's pages forward when the viewer code itself moved — a
// fold rewrites only its own project, so without this the workspace shows two
// designs at once — and pruning links whose checkout is gone.
//
// Others are folded only when the viewer moved, so a sweep over an unchanged
// viewer still costs one project.
export function foldWorkspace(storeDir: string, active?: string): void
{
    reportPruned(pruneDeadLinks(storeDir));
    const moved = chromeStale(storeDir);
    if (active !== undefined)
    {
        foldProject(storeDir, active);
    }
    const others = moved ? readRegistry(storeDir).filter((entry) => entry.slug !== active) : [];
    for (const entry of others)
    {
        foldProject(storeDir, entry.slug);
    }
    claimChrome(storeDir);
    if (others.length > 0)
    {
        notice(`viewer updated — refolded ${others.length} other project${others.length === 1 ? "" : "s"}`);
    }
}

// Every project, whatever the viewer is doing: a pulled log, a cloned store
// and a changed view setting all move state the pages of every project are
// rendered from.
export function foldEveryProject(storeDir: string): void
{
    reportPruned(pruneDeadLinks(storeDir));
    for (const entry of readRegistry(storeDir))
    {
        foldProject(storeDir, entry.slug);
    }
    claimChrome(storeDir);
}

// Pruning is stated, never quiet: the link is gone from resolution from here
// on, and the one way back is the same re-link the stale-link warning names.
function reportPruned(pruned: PrunedLink[]): void
{
    for (const link of pruned)
    {
        notice(`pruned the link to ${link.path} — no checkout there any more; ` +
            `run \`self project link ${link.slug} --here\` in it if it comes back`);
    }
}

// An objective keeps a file of its own while it is live, exactly as an open
// work unit does; closing it removes the file without touching the log that
// still holds its whole lineage.
function foldObjectives(dir: string, hashes: Record<string, string>, model: ProjectModel): void
{
    if (model.goals.objectives.length === 0)
    {
        return;
    }
    ensureDir(join(dir, "objective"));
    const open = new Set(openObjectives(model.goals).map((objective) => objective.id));
    for (const objective of model.goals.objectives)
    {
        const rel = join("objective", `${objective.id}.md`);
        if (open.has(objective.id))
        {
            writeGenerated(dir, hashes, rel, GENERATED_NOTE + "\n\n" + renderObjectiveBody(objective));
        }
        else
        {
            drop(dir, hashes, rel);
        }
    }
}

// A change set keeps a file while it is in the train. Merging or closing it
function drop(dir: string, hashes: Record<string, string>, rel: string): void
{
    rmSync(join(dir, rel), { force: true });
    delete hashes[rel];
}

function readHashes(dir: string): Record<string, string>
{
    const file = join(dir, ".hashes.json");
    return existsSync(file) ? JSON.parse(readFileSync(file, "utf8")) : {};
}

function writeGenerated(dir: string, hashes: Record<string, string>, rel: string, content: string): void
{
    const file = join(dir, rel);
    const recorded = hashes[rel];
    if (recorded !== undefined && existsSync(file) && sha(readFileSync(file, "utf8")) !== recorded)
    {
        console.error(`${errYellow("warning:")} ${rel} was edited by hand — overwriting; state changes must go through events`);
    }
    writeFileSync(file, content);
    hashes[rel] = sha(content);
}

function sha(content: string): string
{
    return createHash("sha256").update(content).digest("hex");
}

function renderState(model: ProjectModel): string
{
    const lines: string[] = [GENERATED_NOTE, "", `# ${model.slug}`, ""];
    if (model.description !== undefined)
    {
        lines.push(model.description, "");
    }
    // Every goal, not the newest: this file has the room, and a project
    // aiming at three outcomes reads as one that abandoned two if only the
    // last one recorded renders.
    lines.push("## Goal", "", ...goalLines(model), "");
    section(lines, "Objectives", objectiveLines(model));
    section(lines, "Proposed work", proposalSummaryLines(model));
    section(lines, "Decisions", decisionLines(model.decisions.filter((d) => d.status === "confirmed")));
    section(lines, "Proposed decisions", proposalLines(model.decisions));
    section(lines, "Conventions", currentConventions(model.conventions).map((c) => `- ${c.text} _(${c.id})_`));
    section(lines, "Work in progress", model.works.filter((w) => w.status === "active").map(workLine));
    section(lines, "Blocked", model.works.filter((w) => w.status === "blocked").map(blockedLine));
    section(lines, "Next", model.works.filter((w) => w.status === "next").map((w) => `- **${w.id}** ${w.outcome}`));
    section(lines, "Open questions", model.openQuestions.map((q) => `- ${q}`));
    section(lines, "Health", model.health.map((h) => `- ${h}`));
    return lines.join("\n").replace(/\n+$/, "\n");
}

// One goal renders as the paragraph it always was; several render as a list,
// so the file never has to claim one of them is the goal.
function goalLines(model: ProjectModel): string[]
{
    const goals = liveGoals(model);
    if (goals.length === 0)
    {
        return [model.goal ?? "_not set_"];
    }
    return goals.length === 1 ? [goals[0].text] : goals.map((goal) => `- ${goal.text} _(${goal.id})_`);
}

function section(lines: string[], title: string, items: string[]): void
{
    if (items.length === 0)
    {
        return;
    }
    lines.push(`## ${title}`, "", ...items, "");
}

// The long-term goal above stays exactly where it is: an objective is a
// time-boxed target beside it, never a replacement for it.
function objectiveLines(model: ProjectModel): string[]
{
    const lines: string[] = [];
    for (const objective of openObjectives(model.goals))
    {
        const box = [objective.horizon, objective.target === undefined ? "" : `target ${objective.target}`]
            .filter((part) => part !== undefined && part !== "").join(", ");
        const proposed = objective.status === "proposed" ? " _(proposed)_" : "";
        lines.push(`- **${objective.id}** ${objective.outcome}${box === "" ? "" : ` (${box})`} — ` +
            `${objective.state}: ${objective.reason}${proposed}`);
        for (const milestone of objective.milestones)
        {
            lines.push(`  - **${milestone.id}** ${milestone.outcome}` +
                `${milestone.target === undefined ? "" : ` (target ${milestone.target})`} — ${milestone.state}: ${milestone.reason}`);
        }
    }
    return lines;
}

function proposalSummaryLines(model: ProjectModel): string[]
{
    return openProposals(model.goals).map((proposal) =>
        `- ${proposal.outcome} → ${proposal.milestone ?? proposal.objective} — ${proposal.confidence} confidence, ` +
        `${proposal.capacity}, expires ${proposal.expires} _(\`self work accept ${proposal.id}\`)_`);
}

function decisionLines(decisions: DecisionState[]): string[]
{
    return decisions.map((decision) =>
    {
        const why = decision.why === undefined ? "" : ` — ${decision.why}`;
        return `- ${decision.text}${why} _(${day(decision.ts)}, ${decision.id})_`;
    });
}

function proposalLines(decisions: DecisionState[]): string[]
{
    return decisions
        .filter((decision) => decision.status === "proposed" && !decision.expired)
        .map((decision) => `- ${decision.text} _(proposed ${day(decision.ts)} — \`self decide confirm ${decision.id}\`)_`);
}

function workLine(work: WorkState): string
{
    const latest = work.reports[work.reports.length - 1];
    const report = latest === undefined ? "" : ` — ${latest.text}`;
    const next = work.next === undefined ? "" : ` (next: ${work.next})`;
    return `- **${work.id}** ${work.outcome}${report}${next}`;
}

function blockedLine(work: WorkState): string
{
    const why = work.blockedWhy === undefined ? "" : `: ${work.blockedWhy}`;
    return `- **${work.id}** ${work.outcome} — waiting on ${work.blockedOn}${why}`;
}

function objectiveHeadLines(objective: ObjectiveState): string[]
{
    const lines: string[] = [];
    if (objective.horizon !== undefined || objective.target !== undefined)
    {
        lines.push(`- Timebox: ${objective.horizon ?? "unset"}${objective.target === undefined ? "" : `, target ${objective.target}`}`);
    }
    if (objective.priority !== undefined)
    {
        lines.push(`- Priority: ${objective.priority}`);
    }
    lines.push(`- Progress: ${objective.met} of ${objective.total} exit criteria covered`);
    if (objective.supersedes.length > 0)
    {
        lines.push(`- Supersedes: ${objective.supersedes.join(", ")}`);
    }
    if (objective.supersededBy !== undefined)
    {
        lines.push(`- Superseded by: ${objective.supersededBy}`);
    }
    lines.push(...carriedLines(objective));
    return lines;
}

// What a revision carried away (#333), grouped by where it went: the plan
// moved to the successor, and this page says so rather than reading as an
// objective whose checkpoints all closed.
function carriedLines(objective: ObjectiveState): string[]
{
    const byTarget = new Map<string, string[]>();
    for (const item of objective.carried)
    {
        byTarget.set(item.to, [...byTarget.get(item.to) ?? [], item.milestone]);
    }
    return [...byTarget.entries()].map(([to, milestones]) => `- Milestones carried to ${to}: ${milestones.join(", ")}`);
}

// `linked` is the read-time merge of the objective's open units across every
// registered project (#244), passed only by the console show: the canonical
// page a fold writes must depend on this project's log alone, so the fold
// passes nothing and the line stays off that page.
export function renderObjectiveBody(objective: ObjectiveState, linked: string[] = []): string
{
    const lines: string[] = [`# ${objective.id} — ${objective.outcome}`, "", `- Status: ${objective.status}`,
        `- Target state: ${objective.state} — ${objective.reason}`, `- Revision: ${objective.revision}`,
        ...objectiveHeadLines(objective),
        ...(linked.length === 0 ? [] : [`- Work: ${linked.join(", ")}`]), ""];
    bullets(lines, "Success criteria", objective.success);
    bullets(lines, "Stop criteria", objective.stop);
    bullets(lines, "Revision history", objective.history.map((entry) => `revision ${entry.revision} on ${day(entry.ts)} — ${entry.why}`));
    for (const milestone of objective.milestones)
    {
        lines.push(`## Milestone ${milestone.id}`, "", renderMilestoneBody(milestone, objective).split("\n").slice(2).join("\n"));
    }
    return lines.join("\n").replace(/\n+$/, "\n");
}

function milestoneHeadLines(milestone: MilestoneState): string[]
{
    const lines: string[] = [];
    if (milestone.target !== undefined)
    {
        lines.push(`- Target: ${milestone.target}`);
    }
    if (milestone.after.length > 0)
    {
        lines.push(`- After: ${milestone.after.join(", ")}`);
    }
    if (milestone.carriedFrom.length > 0)
    {
        lines.push(`- Carried from: ${milestone.carriedFrom.join(", ")}`);
    }
    lines.push(`- Critical path: ${milestone.criticalPath ? "yes" : "no"}`);
    lines.push(`- Work: ${milestone.works.length === 0 ? "none linked" : milestone.works.join(", ")}`);
    if (milestone.evidence.length > 0)
    {
        lines.push(`- Evidence: ${milestone.evidence.join(", ")}`);
    }
    return [...lines, ...reachLines(milestone)];
}

function reachLines(milestone: MilestoneState): string[]
{
    const lines: string[] = [];
    if (milestone.reached !== undefined)
    {
        lines.push(`- Reached: ${reachedLine(milestone.reached)}`);
    }
    if (milestone.reaffirmed !== undefined)
    {
        lines.push(`- Rechecked: ${reachedLine(milestone.reaffirmed)}`);
    }
    return lines;
}

export function renderMilestoneBody(milestone: MilestoneState, objective: ObjectiveState): string
{
    const lines: string[] = [`# ${milestone.id} — ${milestone.outcome}`, "",
        `- Objective: ${objective.id} ${objective.outcome}`,
        `- State: ${milestone.state} — ${milestone.reason}`,
        `- Revision: ${milestone.revision} (objective revision ${objective.revision})`,
        ...milestoneHeadLines(milestone), ""];
    bullets(lines, "Exit criteria", exitLines(milestone));
    bullets(lines, "Coverage", milestone.coverage.map(coverageLine));
    return lines.join("\n").replace(/\n+$/, "\n");
}

function exitLines(milestone: MilestoneState): string[]
{
    return milestone.exit.map((criterion) =>
    {
        const state = criterion.dropped === true ? "dropped"
            : milestone.met.includes(criterion.id) ? "covered" : "open";
        return `${criterion.id} — ${criterion.text} _(${state})_`;
    });
}

function reachedLine(reached: Reached): string
{
    return `${day(reached.ts)} against objective revision ${reached.objectiveRevision}` +
        `/milestone revision ${reached.milestoneRevision}, criteria ${reached.criteria.join(", ")}` +
        `${reached.evidence.length === 0 ? "" : `, evidence ${reached.evidence.join(", ")}`}`;
}

function coverageLine(coverage: Coverage): string
{
    const from = [coverage.work, ...coverage.commits].filter((part) => part !== undefined).join(" ");
    return `${coverage.criterion} on ${day(coverage.ts)} — ${coverage.why}` +
        `${from === "" ? "" : ` [${from}]`} _(${coverage.recheck === true ? "rechecked at " : ""}` +
        `revision ${coverage.objectiveRevision}/${coverage.milestoneRevision})_`;
}

// The semantic half of done, on the page a person reads before closing a unit:
// what it still owes, whether a human has answered, and what its implementation
// had to be. Every line is derived — none of it is asserted by a transition.
function completionLines(work: WorkState): string[]
{
    const completion = work.completion;
    const lines: string[] = [];
    if (completion.approvalRequired !== undefined)
    {
        const granted = completion.approvals.find((item) => item.humanConfirmed);
        lines.push(`- Approval: ${granted === undefined
            ? `required and not granted${completion.approvalRequired.why === undefined ? "" : ` — ${completion.approvalRequired.why}`}`
            : `granted ${day(granted.ts)} by ${granted.by} (${granted.method})`}`);
    }
    if (completion.policy !== undefined)
    {
        const parts = [
            completion.policy.model === undefined ? "" : `model ${completion.policy.model}`,
            completion.policy.freshReview ? "fresh-session review" : ""
        ].filter((part) => part !== "");
        lines.push(`- Completion policy: ${parts.join(", ")}`);
    }
    // A retired unit owes nothing: its outcome was given up, and the advice
    // the owes line carries (`work met`, approval) is refused on it anyway.
    if (work.owes !== undefined && work.status !== "retired")
    {
        lines.push(`- Not done yet: ${work.owes}`);
    }
    return lines;
}

function requirementLines(work: WorkState): string[]
{
    const completion = work.completion;
    return completion.requirements.map((requirement) =>
    {
        const covered = completion.coverage.filter((item) => item.requirement === requirement.id);
        const latest = covered[covered.length - 1];
        const state = requirement.retired === true ? "retired"
            : latest === undefined ? "uncovered"
            : latest.revision === requirement.revision ? `covered ${day(latest.ts)} — ${latest.why}`
            : `covered at revision ${latest.revision}, now revision ${requirement.revision} — recheck it`;
        return `${requirement.id} — ${requirement.text} _(${state})_`;
    });
}

function contributionLines(work: WorkState, model: ProjectModel): string[]
{
    // A foreign contribution names its objective and owning slug only: the
    // outcome and state live in the owner's fold, which this render — also
    // written to canonical pages — must never read (#244 C7).
    return [
        ...contributionsOf(model.goals, work).map((item) =>
            `${item.id} ${item.outcome} (${item.state}${item.criticalPath ? ", critical path" : ""})`),
        ...foreignToward(work)
    ];
}

function bullets(lines: string[], title: string, items: string[]): void
{
    if (items.length > 0)
    {
        lines.push(`## ${title}`, "", ...items.map((item) => `- ${item}`), "");
    }
}

function renderWork(work: WorkState, model: ProjectModel, verdicts: Record<string, Verdict>): string
{
    return GENERATED_NOTE + "\n\n" + renderWorkBody(work, model, verdicts);
}

// What a retirement adds to a unit's record: its own reason and successor,
// then the provenance of any outcome it carries forward. Same-project
// predecessors fold deterministically — both units live in this model, so
// the line can never go stale. Cross-project ones arrive through
// `supersedes`, derived at read time by the caller that can scan.
function retirementLines(model: ProjectModel, work: WorkState, supersedes: string[]): string[]
{
    const lines: string[] = [];
    if (work.status === "retired")
    {
        const successor = work.successor === undefined ? ""
            : ` — successor ${work.successor.work}${work.successor.project === undefined ? "" : ` (${work.successor.project})`}`;
        lines.push(`- Retired: ${work.retiredWhy}${successor}`);
    }
    lines.push(...[...supersededIn(model, work), ...supersedes].map((source) => `- Supersedes: ${source}`));
    return lines;
}

function supersededIn(model: ProjectModel, work: WorkState): string[]
{
    return model.works
        .filter((item) => item.status === "retired" && item.successor?.work === work.id
            && (item.successor.project === undefined || item.successor.project === model.slug))
        .map((item) => `${item.id} — ${item.retiredWhy}`);
}

// Which branches still carry this unit's evidence — the same per-branch
// statement `self context` and `self status` make, derived at the same site
// and scoped to one unit. Absent when every commit it reported is settled, and
// absent on a closed unit, whose verdicts no fold rechecks.
//
// Derived rather than read off `model.unshipped`, because the fold refreshes
// the verdicts after it folds the model: this body renders against the
// verdicts this run just recomputed, and the model's copy is the run before.
function workUnshippedLines(work: WorkState, verdicts: Record<string, Verdict>): string[]
{
    const branches = unshippedBranches([work], verdicts);
    if (branches.length === 0)
    {
        return [];
    }
    const stated = branches.map((branch) =>
    {
        const totals = branchTotals(branch);
        return `${branchLabel(branch)} — ${totals.unsettled} of ${totals.evidence} unsettled`;
    });
    return [`- Unshipped commits by branch: ${stated.join("; ")}`];
}

// Where the unit stands: status, what it contributes to, and what stopped it.
function workStandingLines(work: WorkState, model: ProjectModel, supersedes: string[]): string[]
{
    const lines: string[] = [`- Status: ${work.status}`];
    const contributes = contributionLines(work, model);
    if (contributes.length > 0)
    {
        lines.push(`- Contributes to: ${contributes.join("; ")}`);
    }
    if (work.status === "blocked")
    {
        lines.push(`- Blocked on: ${work.blockedOn}${work.blockedWhy === undefined ? "" : ` — ${work.blockedWhy}`}`);
    }
    lines.push(...retirementLines(model, work, supersedes));
    if (work.next !== undefined)
    {
        lines.push(`- Next action: ${work.next}`);
    }
    if (work.process !== undefined)
    {
        // Last-reported only: this render becomes a synced canonical file, so
        // the machine-local liveness judgment stays on `self status`.
        lines.push(`- Process: ${work.process.state}${work.process.code === undefined ? "" : ` (code ${work.process.code})`} at ${work.process.at}`);
    }
    return lines;
}

// What the unit has to show for itself.
function workEvidenceLines(work: WorkState, verdicts: Record<string, Verdict>): string[]
{
    const lines: string[] = [];
    if (work.branches.length > 0)
    {
        lines.push(`- Branches: ${work.branches.join(", ")}`);
    }
    lines.push(...workUnshippedLines(work, verdicts));
    if (work.evidence.length > 0)
    {
        const marked = work.evidence.map((hash) => verdicts[hash] === undefined ? hash : `${hash} (${verdicts[hash]})`);
        lines.push(`- Evidence: ${marked.join(", ")}`);
    }
    if (work.notes.length > 0)
    {
        lines.push(`- Evidence notes: ${work.notes.join("; ")}`);
    }
    if (work.artifacts.length > 0)
    {
        lines.push(`- Artifacts: ${work.artifacts.map((a) => `${a.id} ${a.name}`).join(", ")}`);
    }
    if (work.attempts.length > 0)
    {
        const attempts = work.attempts.map((a) =>
            `${a.id} (${a.state}${a.failure === undefined ? "" : `: ${a.failure}`})${a.model === undefined ? "" : ` model ${a.model}`}`);
        lines.push(`- Attempts: ${attempts.join(", ")}`);
    }
    return lines;
}

// A multi-line report gets a heading of its own; a one-liner stays a bullet.
function workReportLines(work: WorkState): string[]
{
    if (work.reports.length === 0)
    {
        return [];
    }
    const lines: string[] = ["## Reports (latest first)", ""];
    for (const report of [...work.reports].reverse())
    {
        const commits = report.commits.length > 0 ? ` [${report.commits.join(", ")}]` : "";
        if (report.text.includes("\n"))
        {
            lines.push(`### ${day(report.ts)}${commits}`, "", report.text, "");
        }
        else
        {
            lines.push(`- ${day(report.ts)} — ${report.text}${commits}`);
        }
    }
    lines.push("");
    return lines;
}

export function renderWorkBody(work: WorkState, model: ProjectModel, verdicts: Record<string, Verdict> = {}, supersedes: string[] = []): string
{
    const requirements = requirementLines(work);
    const lines: string[] = [
        `# ${work.id} — ${work.outcome}`,
        "",
        ...workStandingLines(work, model, supersedes),
        ...workEvidenceLines(work, verdicts),
        ...completionLines(work),
        "",
        ...(requirements.length === 0 ? [] : ["## Requirements", "", ...requirements.map((item) => `- ${item}`), ""]),
        ...workReportLines(work)
    ];
    return lines.join("\n").replace(/\n+$/, "\n");
}

function day(ts: string): string
{
    return ts.slice(0, 10);
}
