import { createHash } from "node:crypto";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { refreshBlocks } from "./connect.js";
import { buildModel, CaptureState, DecisionState, DEFAULT_PRIORITY, isClosed, ProjectModel, queueOrder, WorkState } from "./model.js";
import { ensureDir, projectStateDir, readRegistry, readStoreConfig, resolveProjectPath } from "./paths.js";
import { evidenceOf, updateVerdicts, Verdict, verdictSignals } from "./reachability.js";
import { errYellow } from "./style.js";
import { writeViews } from "./view.js";

const GENERATED_NOTE = "<!-- generated by `self` — do not edit; state changes go through events -->";

export function foldProject(storeDir: string, slug: string): void
{
    const model = buildModel(storeDir, slug, new Date());
    const projectDir = resolveProjectPath(storeDir, slug);
    const verdicts = updateVerdicts(storeDir, slug, projectDir, evidenceOf(model.works));
    model.health.push(...verdictSignals(model.works, verdicts));
    const dir = ensureDir(projectStateDir(storeDir, slug));
    ensureDir(join(dir, "work"));
    const hashes = readHashes(dir);
    writeGenerated(dir, hashes, "state.md", renderState(model));
    for (const work of model.works)
    {
        const rel = join("work", `${work.id}.md`);
        if (isClosed(work))
        {
            rmSync(join(dir, rel), { force: true });
            delete hashes[rel];
        }
        else
        {
            writeGenerated(dir, hashes, rel, renderWork(work, verdicts));
        }
    }
    writeFileSync(join(dir, ".hashes.json"), JSON.stringify(hashes, null, 2) + "\n");
    const chromeMoved = writeViews(storeDir, model, readStoreConfig(storeDir), verdicts);
    if (projectDir !== null && existsSync(projectDir))
    {
        refreshBlocks(projectDir, model);
    }
    if (chromeMoved)
    {
        refoldOthers(storeDir, slug);
    }
}

let bringingForward = false;

// A fold only rewrites the project it runs in, so a new viewer would reach
// every other project's pages whenever each next happened to record an
// event — until then the workspace shows two designs at once. When the
// viewer itself moves, bring the rest forward in the same run.
function refoldOthers(storeDir: string, slug: string): void
{
    if (bringingForward)
    {
        return;
    }
    bringingForward = true;
    const others = readRegistry(storeDir).filter((entry) => entry.slug !== slug);
    for (const entry of others)
    {
        foldProject(storeDir, entry.slug);
    }
    bringingForward = false;
    if (others.length > 0)
    {
        console.log(`viewer updated — refolded ${others.length} other project${others.length === 1 ? "" : "s"}`);
    }
}

function readHashes(dir: string): Record<string, string>
{
    const file = join(dir, ".hashes.json");
    return existsSync(file) ? JSON.parse(readFileSync(file, "utf8")) : {};
}

function writeGenerated(dir: string, hashes: Record<string, string>, rel: string, content: string): void
{
    const file = join(dir, rel);
    const recorded = hashes[rel];
    if (recorded !== undefined && existsSync(file) && sha(readFileSync(file, "utf8")) !== recorded)
    {
        console.error(`${errYellow("warning:")} ${rel} was edited by hand — overwriting; state changes must go through events`);
    }
    writeFileSync(file, content);
    hashes[rel] = sha(content);
}

function sha(content: string): string
{
    return createHash("sha256").update(content).digest("hex");
}

function renderState(model: ProjectModel): string
{
    const lines: string[] = [GENERATED_NOTE, "", `# ${model.slug}`, ""];
    if (model.description !== undefined)
    {
        lines.push(model.description, "");
    }
    lines.push("## Goal", "", model.goal ?? "_not set_", "");
    section(lines, "Decisions", decisionLines(model.decisions.filter((d) => d.status === "confirmed")));
    section(lines, "Proposed decisions", proposalLines(model.decisions));
    section(lines, "Conventions", model.conventions.map((c) => `- ${c.text} _(${c.id})_`));
    section(lines, "Work in progress", model.works.filter((w) => w.status === "active").map(workLine));
    section(lines, "Blocked", model.works.filter((w) => w.status === "blocked").map(blockedLine));
    section(lines, "Next", queueOrder(model).map(queuedLine));
    section(lines, "Waiting", model.works.filter((w) => w.waiting !== undefined && !isClosed(w)).map(waitingLine));
    section(lines, "Captured, not routed yet", capturedLines(model.captures));
    section(lines, "Open questions", model.openQuestions.map((q) => `- ${q}`));
    section(lines, "Health", model.health.map((h) => `- ${h}`));
    return lines.join("\n").replace(/\n+$/, "\n");
}

function section(lines: string[], title: string, items: string[]): void
{
    if (items.length === 0)
    {
        return;
    }
    lines.push(`## ${title}`, "", ...items, "");
}

function decisionLines(decisions: DecisionState[]): string[]
{
    return decisions.map((decision) =>
    {
        const why = decision.why === undefined ? "" : ` — ${decision.why}`;
        return `- ${decision.text}${why} _(${day(decision.ts)}, ${decision.id})_`;
    });
}

function proposalLines(decisions: DecisionState[]): string[]
{
    return decisions
        .filter((decision) => decision.status === "proposed" && !decision.expired)
        .map((decision) => `- ${decision.text} _(proposed ${day(decision.ts)} — \`self decide confirm ${decision.id}\`)_`);
}

function workLine(work: WorkState): string
{
    const latest = work.reports[work.reports.length - 1];
    const report = latest === undefined ? "" : ` — ${latest.text}`;
    const next = work.next === undefined ? "" : ` (next: ${work.next})`;
    return `- **${work.id}** ${work.outcome}${report}${next}`;
}

function blockedLine(work: WorkState): string
{
    const why = work.blockedWhy === undefined ? "" : `: ${work.blockedWhy}`;
    return `- **${work.id}** ${work.outcome} — waiting on ${work.blockedOn}${why}`;
}

function queuedLine(work: WorkState): string
{
    const priority = work.priority === DEFAULT_PRIORITY ? "" : ` _(priority ${work.priority})_`;
    return `- **${work.id}** ${work.outcome}${priority}`;
}

function waitingLine(work: WorkState): string
{
    const why = work.waiting === "approval"
        ? `approval: ${work.approval?.why}`
        : `${work.dependsOn.join(", ")}`;
    return `- **${work.id}** ${work.outcome} — waiting on ${why}`;
}

// Directives no one has read yet. They belong in canonical state because a
// capture that only lives in a console is exactly the loss this prevents.
function capturedLines(captures: CaptureState[]): string[]
{
    return captures
        .filter((capture) => capture.link === undefined)
        .map((capture) => `- **${capture.id}** ${firstLine(capture.text)} _(${day(capture.ts)})_`);
}

function firstLine(text: string, max = 160): string
{
    const line = text.split("\n", 1)[0];
    return line.length <= max ? line : line.slice(0, max - 1) + "…";
}

function renderWork(work: WorkState, verdicts: Record<string, Verdict>): string
{
    return GENERATED_NOTE + "\n\n" + renderWorkBody(work, verdicts);
}

export function renderWorkBody(work: WorkState, verdicts: Record<string, Verdict> = {}): string
{
    const lines: string[] = [`# ${work.id} — ${work.outcome}`, "", `- Status: ${work.status}`];
    if (work.status === "blocked")
    {
        lines.push(`- Blocked on: ${work.blockedOn}${work.blockedWhy === undefined ? "" : ` — ${work.blockedWhy}`}`);
    }
    lines.push(...scheduleLines(work));
    if (work.next !== undefined)
    {
        lines.push(`- Next action: ${work.next}`);
    }
    if (work.branches.length > 0)
    {
        lines.push(`- Branches: ${work.branches.join(", ")}`);
    }
    if (work.evidence.length > 0)
    {
        const marked = work.evidence.map((hash) => verdicts[hash] === undefined ? hash : `${hash} (${verdicts[hash]})`);
        lines.push(`- Evidence: ${marked.join(", ")}`);
    }
    if (work.artifacts.length > 0)
    {
        lines.push(`- Artifacts: ${work.artifacts.map((a) => `${a.id} ${a.name}`).join(", ")}`);
    }
    lines.push("");
    if (work.additions.length > 0)
    {
        lines.push("## Added by later directives", "");
        for (const note of work.additions)
        {
            lines.push(`- ${day(note.ts)} — ${note.text} _(${note.capture})_`);
        }
        lines.push("");
    }
    if (work.reports.length > 0)
    {
        lines.push("## Reports (latest first)", "");
        for (const report of [...work.reports].reverse())
        {
            const commits = report.commits.length > 0 ? ` [${report.commits.join(", ")}]` : "";
            if (report.text.includes("\n"))
            {
                lines.push(`### ${day(report.ts)}${commits}`, "", report.text, "");
            }
            else
            {
                lines.push(`- ${day(report.ts)} — ${report.text}${commits}`);
            }
        }
        lines.push("");
    }
    return lines.join("\n").replace(/\n+$/, "\n");
}

// Everything that decides whether this unit may run right now, and who holds
// it while it does. Absent lines mean the default: level priority, no waits,
// no lease.
function scheduleLines(work: WorkState): string[]
{
    const lines: string[] = [];
    if (work.priority !== DEFAULT_PRIORITY)
    {
        lines.push(`- Priority: ${work.priority}`);
    }
    if (work.dependsOn.length > 0)
    {
        lines.push(`- Depends on: ${work.dependsOn.join(", ")}`);
    }
    if (work.approval !== undefined)
    {
        lines.push(`- Approval: ${work.approval.granted ? "granted" : "required"} — ${work.approval.why}`);
    }
    if (work.lease !== undefined)
    {
        lines.push(`- Lease: ${work.lease.worker} until ${work.lease.expires}${work.leaseExpired ? " (expired)" : ""}`);
    }
    return lines;
}

function day(ts: string): string
{
    return ts.slice(0, 10);
}
