// What `self <command> --help` cannot answer. A help page states how to type a
// command; these pages state what the thing is, when to reach for it, and the
// order the verbs go in. An agent working in someone else's project can reach
// the managed block and the binary and nothing else, so the concepts have to
// ship inside the binary or they do not exist for it (#221).
//
// This module holds prose and imports nothing: `help.ts` renders it, and the
// dispatcher resolves a topic only after no command claims the name.

interface Topic
{
    name: string;
    summary: string;
    body: string[];
}

export const TOPICS: Topic[] = [
    {
        name: "agents",
        summary: "how a session drives this CLI, start to finish",
        body: [
            "An agent session reads state, does work, and leaves the state true for the",
            "next session. Three moments carry that.",
            "",
            "  1. Session start — `self context`",
            "",
            "     Everything the project has decided, rendered by priority. Treat it as",
            "     current truth: it is folded from the log, not written by hand. What it",
            "     omits was placed out of the rendered set on purpose, and `self state`",
            "     lists the rest.",
            "",
            "  2. While working — a work unit carries it",
            "",
            "       self work propose \"<plan>\"             # when the plan wants review",
            "       self work start <id>",
            "       self report <id> \"<what happened>\"      # after committing",
            "",
            "     The outcome is what must become true, not the task. Propose it when the",
            "     plan wants review and `work add` it when it does not — both record who",
            "     wrote them, and `self undo` takes either back. `start` is how a",
            "     session reads the brief and the report history, and it records that",
            "     this session took the unit — so a second session is told who is on it",
            "     rather than starting the same work twice. `show` is the same reading",
            "     with nothing recorded. `report` attaches the current HEAD as evidence,",
            "     which is what makes a later done claim admissible.",
            "",
            "  3. Closing — the claim carries evidence",
            "",
            "       self work done <id> --report \"<what verifiably happened>\"",
            "",
            "     A bare claim is refused. See `self help work`.",
            "",
            "What belongs in the log and what belongs in the conversation are different",
            "questions. Records — events, decisions, reports, conventions — are written",
            "in English so whoever opens them next can read them. Answers to the person",
            "go in the person's language.",
            "",
            "Two habits that are cheap now and expensive later:",
            "",
            "  - Register approved work the moment it is approved. A plan that lives",
            "    only in a conversation is lost when the conversation ends.",
            "  - Attach a scoping brief to deferred work — `self report <id> --file",
            "    <path>` with scope, design anchors and known pitfalls. A bare outcome",
            "    line loses the context that produced it.",
            "",
            "Related: `self help work`, `self help records`, `self help context`."
        ]
    },
    {
        name: "context",
        summary: "what `self context` renders, and why something is missing from it",
        body: [
            "`self context` is a projection, not a file. Every asserted record folds",
            "into one entity, and placement decides which of them the projection",
            "renders and in what order.",
            "",
            "Three exposure tiers, each answering a different question:",
            "",
            "  full     rendered whole. What a session cannot work correctly without.",
            "  index    rendered as one line. Enough to know it exists and ask for it.",
            "  search   not rendered. Live, and reached by naming it.",
            "",
            "So a record missing from context is not gone. It was placed at a tier that",
            "does not render, or it was superseded, retracted or retired — and those",
            "three are different from each other (`self help records`).",
            "",
            "Reading around the projection:",
            "",
            "  self state                  every live record with its tier and priority",
            "  self state show <id>        one record, whole",
            "  self search <query>         the live records this projection does not show",
            "  self state show <id> --history   one record's own events, oldest first",
            "",
            "Retention caps bound the rendered tiers so context stays affordable. When",
            "a tier is full, adding to it refuses until something is demoted — see",
            "`self help placement`.",
            "",
            "The managed block in AGENTS.md and CLAUDE.md is a different surface: it is",
            "written into the project repository and loaded by the agent tool every",
            "session, so it stays short and hands detail to these pages."
        ]
    },
    {
        name: "records",
        summary: "one entity behind every record kind, and how a record is corrected",
        body: [
            "Goal, decision, convention, objective, milestone, work — each folds into",
            "the same entity. The preset verbs are spellings over one grammar, not",
            "separate machinery, which is why placement, coverage and correction work",
            "the same way on all of them.",
            "",
            "  self state add \"<text>\" --label <l>     record one, free-labeled",
            "  self alias add <verb>                   make a verb of a label",
            "  self decide \"<text>\" --why \"<reason>\"   the decision spelling",
            "",
            "A record's text is immutable once confirmed. Correcting it does not edit",
            "it — it restates it and carries the lineage:",
            "",
            "  self state add \"<corrected text>\" --supersedes <id>",
            "",
            "Every add verb spells it that way, including a work unit's outcome, where",
            "`--supersedes <id> --why \"<why it moved>\"` also retires the unit it",
            "replaces.",
            "",
            "That is for a record that held and then moved. A record that was a plain",
            "mistake is undone instead, and owes no reason at all:",
            "",
            "  self undo                  take back the newest append",
            "  self undo <event-id>       take back that one",
            "",
            "Supersession says an outcome moved to a successor; an undo says nothing",
            "was there to move. Nothing is deleted either way — the undo is itself an",
            "event, and `self log` keeps both halves.",
            "",
            "Four exits, and they are not interchangeable:",
            "",
            "  supersede   something replaces it — the successor says why",
            "  retract     it no longer holds and nothing replaces it — carries --why",
            "  retire      an outcome given up or moved, never reached — carries --why",
            "  undo        it was a mistake and never held — carries no reason",
            "",
            "Neither retract nor retire is a way to fix wording.",
            "",
            "A cleanup produces a dozen of them at once, and a dozen appends is a dozen",
            "chances for one to be the one that fails. Write them to a file, one per",
            "line, and land the set as one append:",
            "",
            "  self apply <file>",
            "",
            "A record that took any of those three exits leaves what is true now, so",
            "`self search` stops answering for it. Nothing is unreachable: name it, and",
            "`self state show <id>` prints it whole and `--history` its own events.",
            "",
            "A proposal is a record waiting on a person. `--proposed` records one; the",
            "person confirms it. A proposed record never displaces a confirmed one",
            "until it is confirmed itself.",
            "",
            "Related: `self help placement`, `self help goals`."
        ]
    },
    {
        name: "placement",
        summary: "scope, priority and exposure — how a record earns its place in context",
        body: [
            "Placement is three values on every record.",
            "",
            "  scope       which project renders it: this one, another registered one,",
            "              or every one of them",
            "  priority    the order inside a tier, lowest number first",
            "  exposure    full, index or search (`self help context`)",
            "",
            "  self state place <id> [--priority <n>] [--exposure full|index|search]",
            "                       [--scope <slug>|workspace]",
            "",
            "Moving a record toward less rendering is a demotion, and a demotion",
            "records `--why`: a record that left the rendered set with no reason on",
            "record reads, a year later, exactly like one nobody wrote down.",
            "",
            "Demoting out of `full` waits for the person. Pass `--proposed`, and the",
            "user runs `self state confirm <id>`. An agent never quietly stops",
            "rendering something a person put in front of every session.",
            "",
            "Retention caps bound each rendered tier. Past a cap, `state add` and",
            "`state place` refuse until `--demote <id>` names what frees the room:",
            "",
            "  self state add \"<text>\" --demote <id> --proposed",
            "",
            "The add and the demotion then land as a pair waiting on the user, so",
            "nothing is quietly pushed out to make space.",
            "",
            "Scope names where a record renders, never where it is stored. Omit the flag",
            "for the project you are in, name another registered project's slug to move",
            "the record there, or `--scope workspace` to render it everywhere. Its events",
            "stay in the log that already holds them, so brief, reports, artifacts,",
            "evidence and timestamps travel by not moving at all.",
            "",
            "  self state place <id> --scope <slug>     renders there, not here",
            "  self project                             the slugs --scope takes",
            "",
            "A record scoped into this project resolves here — `state place`, `work",
            "start`, `report` and `work done` all answer for it — and every write about",
            "it lands in its home log. `--scope project` was retired: omit the flag.",
            "",
            "`--scope workspace` works on the state and alias verbs. The preset verbs",
            "spell the same placement `--workspace`: `self convention add \"<text>\"",
            "--workspace` for a rule the whole workspace works by, and `self goal add`",
            "or `self objective add` with it for direction that is the company's rather",
            "than one project's — read from inside every registered project, while the",
            "record itself stays in the store of the project it was recorded in."
        ]
    },
    {
        name: "work",
        summary: "the work graph: outcomes, evidence, criteria, and proposals",
        body: [
            "A work unit states an outcome — what must become true — not a task list.",
            "",
            "  self work propose \"<plan>\"              self work start <id>",
            "  self work show <id>                     full brief and report history",
            "  self work                               open units",
            "",
            "Reports are how a unit stays readable to the next session:",
            "",
            "  self report <id> \"<summary>\"            HEAD attached as evidence",
            "  self report <id> --file <path>          a longer brief from a file",
            "  self report <id> --artifact <path>      a file copied into the store",
            "",
            "Done is a judgment, and the claim carries evidence. `self work done <id>`",
            "closes a unit only when a report carries a commit or an artifact, or the",
            "done itself states one:",
            "",
            "  self work done <id> --report \"<what verifiably happened>\"",
            "",
            "Declared criteria gate it further: each must be covered — `self state",
            "cover <id> --criterion \"<c>\" --why \"<how the evidence covers it>\"` —",
            "before the claim is admitted.",
            "",
            "When work stops for a reason that is not completion:",
            "",
            "  self work block <id> --on decision|dependency|external --why \"...\"",
            "  self work retire <id> --why \"...\" [--successor <work-id>]",
            "",
            "Retire is for an outcome given up or moved. Never mark such a unit done,",
            "and never leave it falsely blocked.",
            "",
            "Wrote the plan yourself? Propose it rather than starting it, so the user",
            "reviews the plan and not the result:",
            "",
            "  self work propose \"<plan>\"                 recorded as work waiting on review",
            "  self work revise <id> \"<revised plan>\" --why \"<what changed>\"",
            "",
            "Propose means \"I want this reviewed before I build it\", not \"I am an",
            "agent\": `work add` records the same unit confirmed at once, and both say",
            "who wrote them. The user answers with `self work confirm <id>`.",
            "",
            "One id carries the whole loop. A revision keeps that id, keeps every",
            "earlier version in `self work show <id> --history`, and invalidates the",
            "confirm, so `self work start` is refused until the user confirms again.",
            "The first start freezes the plan; after it, a correction is a successor —",
            "propose that one too:",
            "",
            "  self work propose \"<corrected plan>\" --supersedes <id> --why w",
            "",
            "The named unit is untouched until the confirm, which records the new",
            "unit and retires the one it replaces in one append.",
            "",
            "Found a gap between an objective and current state? The same verb closes",
            "one, with its full brief — value, success, stop, risk, capacity, evidence",
            "plan, confidence, expiry, and the objective or milestone it closes.",
            "`self work --help` lists the flags, and the refusal names every one you",
            "left out at once.",
            "",
            "Related: `self help goals`."
        ]
    },
    {
        name: "goals",
        summary: "long-term goals, objectives, milestones, and what reaching one takes",
        body: [
            "Three levels, and they are separate state.",
            "",
            "  self goal add \"<text>\"                            long-term, open-ended",
            "  self objective add \"<outcome>\" --target <date>    time-boxed",
            "  self milestone add \"<outcome>\" --objective <id> --exit \"<criterion>\"",
            "",
            "  self objective        both levels, with the reason for each state",
            "",
            "A project holds as many goals as it means to. Recording one displaces",
            "nothing: the goal a new one replaces is named with `--supersedes <id>`,",
            "and one given up leaves through `self goal retract <id> --why w`.",
            "",
            "A milestone declares its exit criteria when it is created. Reaching it is",
            "not a matter of finishing the work under it — every criterion has to be",
            "covered first, each with the evidence that covers it:",
            "",
            "  self milestone met <id> --criterion <c> --why \"<how it covers it>\"",
            "  self milestone reach <id>",
            "",
            "Finishing work never reaches a milestone on its own, and progress is",
            "never a percentage: a criterion is covered or it is not.",
            "",
            "Revising an objective or a milestone leaves what it already settled",
            "stale — coverage binds to the record, and a revision is a new record.",
            "Re-judge it at the current revision:",
            "",
            "  self milestone recheck <id> --criterion <c> --why \"<what you re-judged>\"",
            "",
            "State what a unit contributes to with `self work link <id> --milestone",
            "<id>`. That is what makes an objective answerable: which work moves it.",
            "",
            "Related: `self help work`."
        ]
    },
    {
        name: "workspace",
        summary: "the store, the projects in it, and moving it between machines",
        body: [
            "State lives in a workspace store outside every code repository, so a",
            "project's history and its state are versioned separately.",
            "",
            "  self init                    make the current directory a workspace",
            "  self project init            register this directory and write its agent block",
            "  self project link [slug]     where a registered project is linked on this machine",
            "  self project link <slug> --here   attach this directory to it (or name a path)",
            "  self project unlink <slug> <path> detach one again — a directory that is gone too",
            "  self setup                   what this directory resolves to",
            "",
            "`project init` takes no path — it registers the directory it runs in, and",
            "`--name <slug>` is how a project is named something other than that",
            "directory. Every checkout of a registered repository — worktrees included —",
            "resolves on its own. Never run `self project init` inside another checkout",
            "of a project that is already registered.",
            "",
            "A project nobody is working on is set aside rather than left in the way:",
            "",
            "  self project archive <slug> --why \"<reason>\"    take it out of every listing",
            "  self project restore <slug> [--why \"<reason>\"]  bring it back as it was left",
            "  self project --archived                         what is set aside, and why",
            "",
            "Archiving is not retirement. Open work neither blocks it nor is retired by",
            "it, nothing is recorded into the project until it is restored, and restore",
            "gives every work unit back in the state it was left. An archived project",
            "still reads through `--project <slug>`.",
            "",
            "`restore` is the only way back, and `--why` on it is how an archive that",
            "should never have been written is stated. `self undo` is not a second way:",
            "it reads its project from the working directory, and both verbs above name",
            "a slug so a workspace is tidied from anywhere.",
            "",
            "Moving the store between machines is git, explicitly:",
            "",
            "  self remote add <url>        connect the store to a git remote",
            "  self sync                    pull, refold, push",
            "  self clone <url> [dir]       take the store onto another machine",
            "",
            "Generated files under `.superself/` are folded from the log. Never edit",
            "them by hand — the log is canonical, and the next fold overwrites",
            "anything written beside it.",
            "",
            "The agent block in AGENTS.md and CLAUDE.md is rewritten by the installed",
            "CLI whenever the project records something, and `self connect` rewrites it",
            "on demand. It carries the version that rendered it, so a block written by",
            "an older CLI is visible as one."
        ]
    }
];

export function findTopic(name: string | undefined): Topic | undefined
{
    return name === undefined ? undefined : TOPICS.find((topic) => topic.name === name);
}

export function topicPage(topic: Topic): string
{
    return [`${topic.name} — ${topic.summary}`, ""].concat(topic.body).join("\n");
}
