import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { foldProject } from "./fold.js";
import { commitAll, configureStoreIdentity, excludeLocally, git } from "./gitutil.js";
import { CliContext, ensureDir, LINKS_FILE, readRegistry, STORE_DIR } from "./paths.js";
import { CliError } from "./types.js";

const ATTRIBUTES = [
    "registry.jsonl merge=union",
    "projects/*/log.jsonl merge=union",
    "projects/*/state.md merge=derived",
    "projects/*/work/*.md merge=derived",
    "projects/*/.hashes.json merge=derived"
].join("\n") + "\n";

export function ensureSyncConfig(storeDir: string): void
{
    const file = join(storeDir, ".gitattributes");
    if (!existsSync(file) || readFileSync(file, "utf8") !== ATTRIBUTES)
    {
        writeFileSync(file, ATTRIBUTES);
    }
    git(storeDir, "config", "merge.derived.name", "derived file — regenerated by refold");
    git(storeDir, "config", "merge.derived.driver", "true");
    excludeLocally(storeDir, LINKS_FILE);
}

export function remoteAdd(ctx: CliContext, url: string): void
{
    ensureSyncConfig(ctx.storeDir);
    const existing = git(ctx.storeDir, "remote", "get-url", "origin");
    const result = existing.ok
        ? git(ctx.storeDir, "remote", "set-url", "origin", url)
        : git(ctx.storeDir, "remote", "add", "origin", url);
    if (!result.ok)
    {
        throw new CliError(`git remote failed: ${result.err}`);
    }
    commitAll(ctx.storeDir, "remote add: sync merge attributes");
    console.log(`workspace store now syncs with ${url} — run \`self sync\` to push`);
}

export function syncStore(ctx: CliContext): void
{
    ensureSyncConfig(ctx.storeDir);
    const remote = git(ctx.storeDir, "remote", "get-url", "origin");
    if (!remote.ok)
    {
        throw new CliError("no remote configured — run `self remote add <url>` first");
    }
    commitAll(ctx.storeDir, "sync: local changes");
    const branch = git(ctx.storeDir, "rev-parse", "--abbrev-ref", "HEAD").out;
    pullAndRefold(ctx.storeDir, branch);
    const push = git(ctx.storeDir, "push", "-q", "-u", "origin", branch);
    if (!push.ok)
    {
        throw new CliError(`push failed: ${push.err}`);
    }
    console.log(`synced with ${remote.out}`);
}

function pullAndRefold(storeDir: string, branch: string): void
{
    const fetch = git(storeDir, "fetch", "-q", "origin");
    if (!fetch.ok)
    {
        throw new CliError(`fetch failed: ${fetch.err}`);
    }
    if (!git(storeDir, "rev-parse", "--verify", "-q", `origin/${branch}`).ok)
    {
        return;
    }
    const pull = git(storeDir, "pull", "-q", "--rebase", "origin", branch);
    if (!pull.ok)
    {
        git(storeDir, "rebase", "--abort");
        throw new CliError(`pull failed: ${pull.err} — resolve manually in ${storeDir} and rerun`);
    }
    for (const entry of readRegistry(storeDir))
    {
        foldProject(storeDir, entry.slug);
    }
    commitAll(storeDir, "sync: refold after pull");
}

function storeName(url: string): string
{
    const name = url.replace(/\.git$/, "").split(/[/:]/).filter((part) => part !== "").pop();
    if (name === undefined)
    {
        throw new CliError(`cannot derive a directory name from "${url}" — pass one explicitly`);
    }
    return name;
}

export function cloneStore(url: string, dir: string | undefined): void
{
    const target = resolve(dir ?? storeName(url));
    const storeDir = join(target, STORE_DIR);
    if (existsSync(storeDir))
    {
        throw new CliError(`${target} is already a workspace`);
    }
    ensureDir(target);
    const clone = git(target, "clone", "-q", url, STORE_DIR);
    if (!clone.ok)
    {
        throw new CliError(`clone failed: ${clone.err}`);
    }
    configureStoreIdentity(storeDir);
    ensureSyncConfig(storeDir);
    const slugs = readRegistry(storeDir).map((entry) => entry.slug);
    for (const slug of slugs)
    {
        foldProject(storeDir, slug);
    }
    console.log(`workspace cloned into ${target}`);
    if (slugs.length > 0)
    {
        console.log(`registered projects: ${slugs.join(", ")}`);
        console.log("run `self project link <slug> [path]` from each project's checkout to reconnect it");
    }
}
