import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { foldEveryProject } from "./fold.js";
import { commitAll, configureStoreIdentity, excludeLocally, git, gitPatient } from "./gitutil.js";
import { machineWorkspace, setMachineWorkspace } from "./machine.js";
import { refuseGitOnly } from "./mode.js";
import { notice } from "./output.js";
import { CliContext, ensureDir, EVIDENCE_HEAD_EXCLUDE, LINKS_FILE, readRegistry, STORE_DIR } from "./paths.js";
import { compactionSignal } from "./store.js";
import { CliError, CommandOutput } from "./types.js";

const ATTRIBUTES = [
    "registry.jsonl merge=union",
    "projects/*/log.jsonl merge=union",
    "projects/*/state.md merge=derived",
    "projects/*/work/*.md merge=derived",
    "projects/*/integration/*.md merge=derived",
    "projects/*/.hashes.json merge=derived",
    "projects/*/evidence.json merge=derived"
].join("\n") + "\n";

export function ensureSyncConfig(storeDir: string): void
{
    const file = join(storeDir, ".gitattributes");
    if (!existsSync(file) || readFileSync(file, "utf8") !== ATTRIBUTES)
    {
        writeFileSync(file, ATTRIBUTES);
    }
    git(storeDir, "config", "merge.derived.name", "derived file — regenerated by refold");
    git(storeDir, "config", "merge.derived.driver", "true");
    excludeLocally(storeDir, LINKS_FILE);
    // Derived from this machine's checkout of each project repository, so it
    // has no meaning in another clone and must never be pushed into one.
    excludeLocally(storeDir, EVIDENCE_HEAD_EXCLUDE);
}

export function remoteAdd(ctx: CliContext, url: string): CommandOutput
{
    refuseGitOnly(ctx.storeDir, "remote add", "points a git-backed store at a git remote");
    ensureSyncConfig(ctx.storeDir);
    const existing = git(ctx.storeDir, "remote", "get-url", "origin");
    const result = existing.ok
        ? git(ctx.storeDir, "remote", "set-url", "origin", url)
        : git(ctx.storeDir, "remote", "add", "origin", url);
    if (!result.ok)
    {
        throw new CliError(`git remote failed: ${result.err}`);
    }
    commitAll(ctx.storeDir, "remote add: sync merge attributes");
    return [{ kind: "receipt", text: `workspace store now syncs with ${url} — run \`self sync\` to push` }];
}

export function syncStore(ctx: CliContext): CommandOutput
{
    refuseGitOnly(ctx.storeDir, "sync", "pushes a git-backed store to its git remote");
    ensureSyncConfig(ctx.storeDir);
    const remote = git(ctx.storeDir, "remote", "get-url", "origin");
    if (!remote.ok)
    {
        throw new CliError("no remote configured — run `self remote add <url>` first");
    }
    commitAll(ctx.storeDir, "sync: local changes");
    const branch = git(ctx.storeDir, "rev-parse", "--abbrev-ref", "HEAD").out;
    pullAndRefold(ctx.storeDir, branch);
    const push = gitPatient(ctx.storeDir, "push", "-q", "-u", "origin", branch);
    if (!push.ok)
    {
        throw new CliError(`push failed: ${push.err}`);
    }
    return [{ kind: "receipt", text: `synced with ${remote.out}` }];
}

function pullAndRefold(storeDir: string, branch: string): void
{
    const fetch = gitPatient(storeDir, "fetch", "-q", "origin");
    if (!fetch.ok)
    {
        throw new CliError(`fetch failed: ${fetch.err}`);
    }
    if (!git(storeDir, "rev-parse", "--verify", "-q", `origin/${branch}`).ok)
    {
        return;
    }
    const pull = gitPatient(storeDir, "pull", "-q", "--rebase", "origin", branch);
    if (!pull.ok)
    {
        git(storeDir, "rebase", "--abort");
        throw new CliError(`pull failed: ${pull.err} — resolve manually in ${storeDir} and rerun`);
    }
    foldEveryProject(storeDir);
    commitAll(storeDir, "sync: refold after pull");
    // Said here and nowhere else: the store's size is a workspace fact, so a
    // per-project health signal would repeat it once per project, and `sync`
    // is the deliberate command a person runs with the store in mind. It reads
    // git's own bookkeeping and walks no tree.
    const signal = compactionSignal(storeDir);
    if (signal !== null)
    {
        notice(signal);
    }
}

function storeName(url: string): string
{
    const name = url.replace(/\.git$/, "").split(/[/:]/).filter((part) => part !== "").pop();
    if (name === undefined)
    {
        throw new CliError(`cannot derive a directory name from "${url}" — pass one explicitly`);
    }
    return name;
}

export function cloneStore(url: string, dir: string | undefined): CommandOutput
{
    refuseGitOnlyClone();
    const target = resolve(dir ?? storeName(url));
    const storeDir = join(target, STORE_DIR);
    if (existsSync(storeDir))
    {
        throw new CliError(`${target} is already a workspace`);
    }
    ensureDir(target);
    const clone = gitPatient(target, "clone", "-q", url, STORE_DIR);
    if (!clone.ok)
    {
        throw new CliError(`clone failed: ${clone.err}`);
    }
    configureStoreIdentity(storeDir);
    ensureSyncConfig(storeDir);
    const slugs = readRegistry(storeDir).map((entry) => entry.slug);
    foldEveryProject(storeDir);
    setMachineWorkspace(target);
    return clonedReceipts(target, slugs);
}

// The store this refusal is about is the one the machine already points at, not
// the one about to be made: a clone makes a second git-backed store, and a
// machine whose workspace is server-backed reaches its records by being logged
// in rather than by copying a git history that does not exist. A machine
// pointing at nothing is the ordinary first clone and is not refused.
function refuseGitOnlyClone(): void
{
    const workspaceDir = machineWorkspace();
    if (workspaceDir !== null)
    {
        refuseGitOnly(join(workspaceDir, STORE_DIR), "clone", "copies a git-backed store from a git remote");
    }
}

// Three receipts rather than one with newlines in it: each line is a fact the
// clone recorded, and the reconnection line only exists where there is
// something to reconnect.
function clonedReceipts(target: string, slugs: string[]): CommandOutput
{
    const cloned: CommandOutput = [{ kind: "receipt", text: `workspace cloned into ${target}` }];
    if (slugs.length > 0)
    {
        cloned.push({ kind: "receipt", text: `registered projects: ${slugs.join(", ")}` });
        cloned.push({ kind: "receipt", text: "run `self project link <slug> --here` from each project to reconnect it — once per repository, not once per checkout" });
    }
    return cloned;
}
